name: checks.yml

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get install libcairo2-dev
        python -m pip install --upgrade pip
        pip install flake8 
        pip install black
        pip install mypy
        pip install -U pip setuptools wheel
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        make flake
    - name: Type check with mypy
      run: |
        # stop the build if there are type errors
        make type
    - name: Make sure examples run
      run: |
        python examples/intro.py
        python examples/hanoi.py
        python examples/squares.py
        python examples/escher_square_limit.py
